version: '2'
services:
  teamspeak:
    container_name: teamspeak
    image: silentk/teamspeak:latest
    ports:
        - "9987-9997:9987-9997/udp"
        - "30033:30033"
        - "10011:10011"
    volumes:
        - ./data:/data
    restart: always
